### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by georgedumitru** [CERT-Solucom/certitude#10]
Hello!

I'm running Certitude on a Win7 32bit machine (Python 2.7.10 and all requirements are configured) but when launching the scanner via "python main.py run -c iocscan" I get the error in the printscreen. Please let me know what is the issue in this case.

Regards,
George

![image](https://cloud.githubusercontent.com/assets/13255884/13175629/6c12fbd0-d714-11e5-9fe3-8548404da368.png)

**Comment by CERT-W** [comment]
The error does not appear anymore.
However, it did because you created a profile with no IOC to be scanned.
