### ISSUE TITLE
IOC support

### ISSUE THREAD

**Issue by CGO00** [CERT-Solucom/certitude#11]
Hello,

Just a quick question about STIX, YARA support. 

Did you planned to support another IOC format ?

Thank you

**Comment by Iansus** [comment]
Hi @CGO00,
Support for STIX, Yara and other IOC format is not planned for now.
However, I don't see anything that prevents us from adding it to the medium/long-term roadmap.

Stay tuned,
Regards,

**Comment by Iansus** [comment]
Support for Styx is not in the [roadmap](https://github.com/CERT-W/certitude/wiki#roadmap), but Yara is.
Stay tuned for updates.
