### ISSUE TITLE
Stop using pycrypto, prefer pycryptodome

### ISSUE THREAD

**Issue by maaaaz** [CERT-Solucom/certitude#12]
Hello,
As you may know PyCrypto developement stopped few years ago and some vulns will remained unpatched, for instance [this one](https://blog.sqreen.io/stop-using-pycrypto-use-pycryptodome/).
[Pycryptodome](https://pypi.python.org/pypi/pycryptodome) is a good replacement. 

Cheers.

**Comment by Iansus** [comment]
See #29
