### ISSUE TITLE
KeyError while creating a configuration profile with no yara rule list

### ISSUE THREAD

**Issue by maaaaz** [CERT-Solucom/certitude#18]
Hello,

I encountered a bug while following these steps:
1. Add an IOC file (interface `/config`)
2. Create a new scan profile with a name and selecting the created IOC, but with no yara rule list. **It is accepted by the server.**
3. Go to `/config` and see the following error:
```
KeyError: ''
File "/opt/certitude/components/interface/web.py", line 350, in config
> yaradesclist[cp.id] = '||'.join([yararef[str(id)] for id in cp.yara_list.split(',')])
```

Cheers.

**Comment by Iansus** [comment]
Fixed by f0505dc
