### ISSUE TITLE
Use a python decorator for user authentication on the web interface

### ISSUE THREAD

**Issue by maaaaz** [CERT-Solucom/certitude#19]
Hello,

On the interface, every function starts with `if 'logged_in' in session: else:` structure.
Use a flask decorator such as the one in wavecrack ([definition here](https://github.com/wavestone-cdt/wavecrack/blob/master/cracker/helper.py#L24) and [usage here](https://github.com/wavestone-cdt/wavecrack/blob/master/cracker/routes.py#L55)) as it is more pythonic and gives a less ugly code :)

Cheers

**Comment by Iansus** [comment]
Fixed by 88b7b24
