### ISSUE TITLE
Agent sur les postes de travail/serveurs

### ISSUE THREAD

**Issue by tinque** [CERT-Solucom/certitude#2]
Hello,

Ça serait top d'avoir un agent à déployer sur les postes. En effet une interrogation en PSexec sur les postes avec un compte qui est admin local est top pour le forensic mais pas dans le cadre de la sécu opérationnelle. Cette fonctionnalité pourrait permettre de déployer les agents et d'utiliser l'outil comme outil de supervision en plus d'un outil de forensic !

Bye,

**Comment by CERT-W** [comment]
Bonjour @tinque,

Ce n'est pas prévu en tant que tel dans la roadmap court/moyen terme.
Hors exception, son utilisation principale reste dans le contexte d'une intervention sur incident de sécurité.

++
