### ISSUE TITLE
Improve the readme

### ISSUE THREAD

**Issue by maaaaz** [CERT-Solucom/certitude#23]
Hello,

The current README contains useful information but some info are missing and the order is quite confusing :
* Why the available features come at last ? (`Available modules`)
* Why the software requirements does not first ?  
* Why there is no licence mentioned ?

It would be a good idea to post some screenshots.
Plus, there are some typo (for instance `Runnning`).

All in all, I think that you should follow the same order of [wavecrack's README](https://github.com/wavestone-cdt/wavecrack) which is really nice ;)

Cheers.

**Comment by Iansus** [comment]
See https://github.com/CERT-W/certitude/wiki
