### ISSUE TITLE
Multiple XSRF vulnerabilities

### ISSUE THREAD

**Issue by fschwebel** [CERT-Solucom/certitude#7]
The web interface is not secure enough, even if not published in the local network; an attacker can perform XSRF attacks on all fields and controllers that do not require the current user password to decipher the `MASTER_KEY`.
Exemple: `<img src="1.2.3.4/config/profile/0/delete" />` when included in any webpage visited by an authenticated user, will delete the first user in the database. A local IP can also be used on older browser to perform the attack without the need to know the IP of certitude host.
This attack can also be used to delete IOCs, modify AD credentials so that certitude propagates them in the IS, but not to destroy evidence, as the web interface is read-only on this point.

**Comment by fschwebel** [comment]
Solving #8 would increase the impact of those attacks

**Comment by CERT-W** [comment]
Fixed by b1ab054
